// Generated by scripts/generate_raid_character_mb_texts.mjs. Do not edit manually.
const loaders = Object.freeze({
  'zh-CN': () => import('./characterMbTexts/zh-CN.js'),
  'zh-TW': () => import('./characterMbTexts/zh-TW.js'),
  'en': () => import('./characterMbTexts/en.js'),
  'ja': () => import('./characterMbTexts/ja.js'),
  'ko': () => import('./characterMbTexts/ko.js'),
})
const cache = new Map()

export function loadRaidCharacterMbTexts(locale) {
  const resolvedLocale = loaders[locale] ? locale : 'zh-CN'
  if (!cache.has(resolvedLocale)) {
    cache.set(resolvedLocale, loaders[resolvedLocale]().then(module => module.RAID_CHARACTER_MB_TEXTS))
  }
  return cache.get(resolvedLocale)
}
