export const shopItems = [
  {
    shopKey: 'witch-library-cleanup',
    shopName: '魔女的书库大扫除商城',
    currency: { itemType: 44, itemId: 1, name: '树影书签', iconId: 193 },
    products: [
      { id: 'witch-library-cleanup-001', name: '命运召唤券', tier: 'A', reward: { itemType: 16, itemId: 4, quantity: 5 }, cost: 375, limitTotal: 2, source: 'screenshot' },
      { id: 'witch-library-cleanup-002', name: '星辰的指引召唤券', tier: 'A', reward: { itemType: 16, itemId: 10, quantity: 5 }, cost: 375, limitTotal: 2, source: 'screenshot' },
      { id: 'witch-library-cleanup-003', name: '魔女的奥秘召唤券', tier: 'A', reward: { itemType: 16, itemId: 12, quantity: 10 }, cost: 500, limitTotal: 1, source: 'screenshot' },
      { id: 'witch-library-cleanup-004', name: '圣天使的神谕召唤券', tier: 'A', reward: { itemType: 16, itemId: 1, quantity: 10 }, cost: 500, limitTotal: 1, source: 'screenshot' },
      { id: 'witch-library-cleanup-005', name: '魔女的心片(SR)', tier: 'A', reward: { itemType: 17, itemId: 28, quantity: 20 }, cost: 75, limitTotal: 15, source: 'screenshot' },
      { id: 'witch-library-cleanup-006', name: '魔女的心片(R)', tier: 'A', reward: { itemType: 17, itemId: 27, quantity: 60 }, cost: 40, limitTotal: 50, source: 'screenshot' },
      { id: 'witch-library-cleanup-007', name: '生命树之露', tier: 'A', reward: { itemType: 24, itemId: 1, quantity: 5 }, cost: 300, limitTotal: 1, source: 'screenshot' },
      { id: 'witch-library-cleanup-008', name: '魔水晶', tier: 'A', reward: { itemType: 13, itemId: 1, quantity: 1 }, cost: 30, limitTotal: 10, source: 'screenshot' },
      { id: 'witch-library-cleanup-009', name: '符石兑换券', tier: 'A', reward: { itemType: 13, itemId: 4, quantity: 60 }, cost: 150, limitTotal: 15, source: 'screenshot' },
      { id: 'witch-library-cleanup-010', name: '符石兑换券', tier: 'B', reward: { itemType: 13, itemId: 4, quantity: 5 }, cost: 15, limitTotal: 100, source: 'screenshot' },
      { id: 'witch-library-cleanup-011', name: '强化秘药', tier: 'A', reward: { itemType: 12, itemId: 2, quantity: 20 }, cost: 50, limitTotal: 30, source: 'screenshot' },
      { id: 'witch-library-cleanup-012', name: '魔装高级香油', tier: 'A', reward: { itemType: 15, itemId: 2, quantity: 2 }, cost: 380, limitTotal: 5, source: 'screenshot' },
      { id: 'witch-library-cleanup-013', name: '魔装香油', tier: 'A', reward: { itemType: 15, itemId: 1, quantity: 3 }, cost: 200, limitTotal: 10, source: 'screenshot' },
      { id: 'witch-library-cleanup-014', name: '精炼钢', tier: 'A', reward: { itemType: 13, itemId: 2, quantity: 15000 }, cost: 80, limitTotal: 5, source: 'screenshot' },
      { id: 'witch-library-cleanup-015', name: '圣装钢', tier: 'A', reward: { itemType: 13, itemId: 3, quantity: 1500 }, cost: 120, limitTotal: 5, source: 'screenshot' },
      { id: 'witch-library-cleanup-016', name: '未鉴定符石Lv6', tier: 'A', reward: { itemType: 17, itemId: 9, quantity: 1 }, cost: 16, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-017', name: '未鉴定符石Lv5', tier: 'A', reward: { itemType: 17, itemId: 8, quantity: 1 }, cost: 8, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-018', name: '未鉴定符石Lv4', tier: 'A', reward: { itemType: 17, itemId: 7, quantity: 1 }, cost: 4, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-019', name: '未鉴定符石Lv3', tier: 'A', reward: { itemType: 17, itemId: 6, quantity: 1 }, cost: 2, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-020', name: '未鉴定符石Lv2', tier: 'A', reward: { itemType: 17, itemId: 5, quantity: 1 }, cost: 1, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-021', name: '首领挑战券', tier: 'A', reward: { itemType: 19, itemId: 1, quantity: 1 }, cost: 15, limitTotal: 10, source: 'screenshot' },
      { id: 'witch-library-cleanup-022', name: '无穷之塔挑战券', tier: 'A', reward: { itemType: 20, itemId: 1, quantity: 1 }, cost: 15, limitTotal: 10, source: 'screenshot' },
      { id: 'witch-library-cleanup-023', name: '上级封印宝箱', tier: 'A', reward: { itemType: 17, itemId: 37, quantity: 1 }, cost: 30, limitTotal: 10, source: 'screenshot' },
      { id: 'witch-library-cleanup-024', name: '上级封印宝箱', tier: 'B', reward: { itemType: 17, itemId: 37, quantity: 1 }, cost: 60, limitTotal: 15, source: 'screenshot' },
      { id: 'witch-library-cleanup-025', name: '中级封印宝箱', tier: 'A', reward: { itemType: 17, itemId: 36, quantity: 1 }, cost: 15, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-026', name: '中级封印宝箱', tier: 'B', reward: { itemType: 17, itemId: 36, quantity: 1 }, cost: 30, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-027', name: '初级封印宝箱', tier: 'A', reward: { itemType: 17, itemId: 35, quantity: 1 }, cost: 10, limitTotal: 30, source: 'screenshot' },
      { id: 'witch-library-cleanup-028', name: '初级封印宝箱', tier: 'B', reward: { itemType: 17, itemId: 35, quantity: 1 }, cost: 15, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-029', name: '上级封印钥匙', tier: 'A', reward: { itemType: 18, itemId: 3, quantity: 1 }, cost: 4, limitTotal: null, source: 'screenshot' },
      { id: 'witch-library-cleanup-030', name: '中级封印钥匙', tier: 'A', reward: { itemType: 18, itemId: 2, quantity: 1 }, cost: 2, limitTotal: null, source: 'screenshot' },
      { id: 'witch-library-cleanup-031', name: '初级封印钥匙', tier: 'A', reward: { itemType: 18, itemId: 1, quantity: 1 }, cost: 1, limitTotal: null, source: 'screenshot' },
    ],
  },
  {
    shopKey: 'premium-shop',
    shopName: '精品店',
    tradeShopTabId: 13,
    currency: { itemType: 1, itemId: 1, name: '免费钻石', iconId: 1 },
    products: [
      {
        id: 'premium-shop-076',
        treasureChestId: 76,
        name: '武具强化材料礼盒',
        iconId: 92,
        reward: { itemType: 9, itemId: 76, quantity: 1 },
        contents: [
          { itemType: 12, itemId: 2, quantity: 200 },
          { itemType: 13, itemId: 4, quantity: 200 },
        ],
        cost: 9900,
        limitTotal: 1,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-080',
        treasureChestId: 80,
        name: '圣装钢礼盒',
        iconId: 95,
        reward: { itemType: 9, itemId: 80, quantity: 1 },
        contents: [
          { itemType: 13, itemId: 3, quantity: 48000 },
          { itemType: 12, itemId: 2, quantity: 100 },
        ],
        cost: 9900,
        limitTotal: 1,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-081',
        treasureChestId: 81,
        name: '精炼钢礼盒',
        iconId: 96,
        reward: { itemType: 9, itemId: 81, quantity: 1 },
        contents: [
          { itemType: 13, itemId: 2, quantity: 580000 },
          { itemType: 12, itemId: 2, quantity: 100 },
        ],
        cost: 9900,
        limitTotal: 1,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-082',
        treasureChestId: 82,
        name: '金币礼盒',
        iconId: 101,
        reward: { itemType: 9, itemId: 82, quantity: 1 },
        contents: [
          { itemType: 10, itemId: 5, quantity: 3 },
          { itemType: 12, itemId: 1, quantity: 800 },
        ],
        cost: 1200,
        limitTotal: 3,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-083',
        treasureChestId: 83,
        name: '封印宝箱礼盒',
        iconId: 102,
        reward: { itemType: 9, itemId: 83, quantity: 1 },
        contents: [
          { itemType: 17, itemId: 35, quantity: 5 },
          { itemType: 17, itemId: 36, quantity: 10 },
          { itemType: 17, itemId: 37, quantity: 20 },
          { itemType: 19, itemId: 1, quantity: 16 },
          { itemType: 10, itemId: 11, quantity: 1 },
        ],
        cost: 1560,
        limitTotal: 3,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-084',
        treasureChestId: 84,
        name: '封印钥匙礼盒',
        iconId: 103,
        reward: { itemType: 9, itemId: 84, quantity: 1 },
        contents: [
          { itemType: 18, itemId: 1, quantity: 10 },
          { itemType: 18, itemId: 2, quantity: 20 },
          { itemType: 18, itemId: 3, quantity: 50 },
          { itemType: 20, itemId: 1, quantity: 16 },
          { itemType: 10, itemId: 11, quantity: 1 },
        ],
        cost: 1560,
        limitTotal: 3,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-085',
        treasureChestId: 85,
        name: '魔女的来信(R・忧蓝)礼袋',
        iconId: 104,
        reward: { itemType: 9, itemId: 85, quantity: 1 },
        contents: [
          { itemType: 17, itemId: 17, quantity: 3 },
          { itemType: 19, itemId: 1, quantity: 4 },
          { itemType: 20, itemId: 1, quantity: 4 },
        ],
        cost: 660,
        limitTotal: 1,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-086',
        treasureChestId: 86,
        name: '魔女的来信(R・业红)礼袋',
        iconId: 104,
        reward: { itemType: 9, itemId: 86, quantity: 1 },
        contents: [
          { itemType: 17, itemId: 18, quantity: 3 },
          { itemType: 19, itemId: 1, quantity: 4 },
          { itemType: 20, itemId: 1, quantity: 4 },
        ],
        cost: 660,
        limitTotal: 1,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-087',
        treasureChestId: 87,
        name: '魔女的来信(R・苍翠)礼袋',
        iconId: 104,
        reward: { itemType: 9, itemId: 87, quantity: 1 },
        contents: [
          { itemType: 17, itemId: 19, quantity: 3 },
          { itemType: 19, itemId: 1, quantity: 4 },
          { itemType: 20, itemId: 1, quantity: 4 },
        ],
        cost: 660,
        limitTotal: 1,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-088',
        treasureChestId: 88,
        name: '魔女的来信(R・流金)礼袋',
        iconId: 104,
        reward: { itemType: 9, itemId: 88, quantity: 1 },
        contents: [
          { itemType: 17, itemId: 20, quantity: 3 },
          { itemType: 19, itemId: 1, quantity: 4 },
          { itemType: 20, itemId: 1, quantity: 4 },
        ],
        cost: 660,
        limitTotal: 1,
        source: 'screenshot',
      },
    ],
  },
]
