import { GUILD_RAID_UNIQUE_WEAPON_FRAGMENT_KEY } from '../engine/derivedScores.js'

const names = (nameZh, nameTw, nameEn, nameJa, nameKo) => ({
  name: nameZh,
  nameZh,
  nameTw,
  nameEn,
  nameJa,
  nameKo,
})

export const shopItems = [
  {
    shopKey: 'witch-library-cleanup',
    ...names('魔女的书库大扫除商城', '魔女的書庫大掃除商城', 'Spellbook Sweep Shop', '魔女の書庫整理ショップ', '마녀의 서재 대청소 상점'),
    shopName: '魔女的书库大扫除商城',
    currency: { itemType: 44, itemId: 1, iconId: 193, ...names('树影书签', '樹影書籤', 'Arbored Bookmark', '木漏れ日の栞', '숲 정령의 책갈피') },
    products: [
      { id: 'witch-library-cleanup-001', name: '命运召唤券', tier: 'A', reward: { itemType: 16, itemId: 4, quantity: 5 }, cost: 375, limitTotal: 2, source: 'screenshot' },
      { id: 'witch-library-cleanup-002', name: '星辰的指引召唤券', tier: 'A', reward: { itemType: 16, itemId: 10, quantity: 5 }, cost: 375, limitTotal: 2, source: 'screenshot' },
      { id: 'witch-library-cleanup-003', name: '魔女的奥秘召唤券', tier: 'A', reward: { itemType: 16, itemId: 12, quantity: 10 }, cost: 500, limitTotal: 1, source: 'screenshot' },
      { id: 'witch-library-cleanup-004', name: '圣天使的神谕召唤券', tier: 'A', reward: { itemType: 16, itemId: 1, quantity: 10 }, cost: 500, limitTotal: 1, source: 'screenshot' },
      { id: 'witch-library-cleanup-005', name: '魔女的心片(SR)', tier: 'A', reward: { itemType: 17, itemId: 28, quantity: 20 }, cost: 75, limitTotal: 15, source: 'screenshot' },
      { id: 'witch-library-cleanup-006', name: '魔女的心片(R)', tier: 'A', reward: { itemType: 17, itemId: 27, quantity: 60 }, cost: 40, limitTotal: 50, source: 'screenshot' },
      { id: 'witch-library-cleanup-007', name: '生命树之露', tier: 'A', reward: { itemType: 24, itemId: 1, quantity: 5 }, cost: 300, limitTotal: 1, source: 'screenshot' },
      { id: 'witch-library-cleanup-008', name: '魔水晶', tier: 'A', reward: { itemType: 13, itemId: 1, quantity: 1 }, cost: 30, limitTotal: 10, source: 'screenshot' },
      { id: 'witch-library-cleanup-009', name: '符石兑换券', tier: 'A', reward: { itemType: 13, itemId: 4, quantity: 60 }, cost: 150, limitTotal: 15, source: 'screenshot' },
      { id: 'witch-library-cleanup-010', name: '符石兑换券', tier: 'B', reward: { itemType: 13, itemId: 4, quantity: 5 }, cost: 15, limitTotal: 100, source: 'screenshot' },
      { id: 'witch-library-cleanup-011', name: '强化秘药', tier: 'A', reward: { itemType: 12, itemId: 2, quantity: 20 }, cost: 50, limitTotal: 30, source: 'screenshot' },
      { id: 'witch-library-cleanup-012', name: '魔装高级香油', tier: 'A', reward: { itemType: 15, itemId: 2, quantity: 2 }, cost: 380, limitTotal: 5, source: 'screenshot' },
      { id: 'witch-library-cleanup-013', name: '魔装香油', tier: 'A', reward: { itemType: 15, itemId: 1, quantity: 3 }, cost: 200, limitTotal: 10, source: 'screenshot' },
      { id: 'witch-library-cleanup-014', name: '精炼钢', tier: 'A', reward: { itemType: 13, itemId: 2, quantity: 15000 }, cost: 80, limitTotal: 5, source: 'screenshot' },
      { id: 'witch-library-cleanup-015', name: '圣装钢', tier: 'A', reward: { itemType: 13, itemId: 3, quantity: 1500 }, cost: 120, limitTotal: 5, source: 'screenshot' },
      { id: 'witch-library-cleanup-016', name: '未鉴定符石Lv6', tier: 'A', reward: { itemType: 17, itemId: 9, quantity: 1 }, cost: 16, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-017', name: '未鉴定符石Lv5', tier: 'A', reward: { itemType: 17, itemId: 8, quantity: 1 }, cost: 8, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-018', name: '未鉴定符石Lv4', tier: 'A', reward: { itemType: 17, itemId: 7, quantity: 1 }, cost: 4, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-019', name: '未鉴定符石Lv3', tier: 'A', reward: { itemType: 17, itemId: 6, quantity: 1 }, cost: 2, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-020', name: '未鉴定符石Lv2', tier: 'A', reward: { itemType: 17, itemId: 5, quantity: 1 }, cost: 1, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-021', name: '首领挑战券', tier: 'A', reward: { itemType: 19, itemId: 1, quantity: 1 }, cost: 15, limitTotal: 10, source: 'screenshot' },
      { id: 'witch-library-cleanup-022', name: '无穷之塔挑战券', tier: 'A', reward: { itemType: 20, itemId: 1, quantity: 1 }, cost: 15, limitTotal: 10, source: 'screenshot' },
      { id: 'witch-library-cleanup-023', name: '上级封印宝箱', tier: 'A', reward: { itemType: 17, itemId: 37, quantity: 1 }, cost: 30, limitTotal: 10, source: 'screenshot' },
      { id: 'witch-library-cleanup-024', name: '上级封印宝箱', tier: 'B', reward: { itemType: 17, itemId: 37, quantity: 1 }, cost: 60, limitTotal: 15, source: 'screenshot' },
      { id: 'witch-library-cleanup-025', name: '中级封印宝箱', tier: 'A', reward: { itemType: 17, itemId: 36, quantity: 1 }, cost: 15, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-026', name: '中级封印宝箱', tier: 'B', reward: { itemType: 17, itemId: 36, quantity: 1 }, cost: 30, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-027', name: '初级封印宝箱', tier: 'A', reward: { itemType: 17, itemId: 35, quantity: 1 }, cost: 10, limitTotal: 30, source: 'screenshot' },
      { id: 'witch-library-cleanup-028', name: '初级封印宝箱', tier: 'B', reward: { itemType: 17, itemId: 35, quantity: 1 }, cost: 15, limitTotal: 20, source: 'screenshot' },
      { id: 'witch-library-cleanup-029', name: '上级封印钥匙', tier: 'A', reward: { itemType: 18, itemId: 3, quantity: 1 }, cost: 4, limitTotal: Infinity, source: 'screenshot' },
      { id: 'witch-library-cleanup-030', name: '中级封印钥匙', tier: 'A', reward: { itemType: 18, itemId: 2, quantity: 1 }, cost: 2, limitTotal: Infinity, source: 'screenshot' },
      { id: 'witch-library-cleanup-031', name: '初级封印钥匙', tier: 'A', reward: { itemType: 18, itemId: 1, quantity: 1 }, cost: 1, limitTotal: Infinity, source: 'screenshot' },
    ],
  },
  {
    shopKey: 'guild-raid',
    ...names('公会讨伐战商城', '公會討伐戰商城', 'Guild Raid Shop', 'ギルドレイドショップ', '길드 레이드 상점'),
    shopName: '公会讨伐战商城',
    currency: { itemType: null, itemId: null, iconId: 0, variableName: true, ...names('公会讨伐战活动代币', '公會討伐戰活動代幣', 'Guild Raid event token', 'ギルドレイドイベントメダル', '길드 레이드 이벤트 토큰') },
    products: [
      { id: 'guild-raid-001', name: '命运召唤券', tier: 'A', reward: { itemType: 16, itemId: 4, quantity: 1 }, cost: 75, limitTotal: 10, source: 'screenshot' },
      { id: 'guild-raid-002', name: '星辰的指引召唤券', tier: 'A', reward: { itemType: 16, itemId: 10, quantity: 1 }, cost: 75, limitTotal: 10, source: 'screenshot' },
      { id: 'guild-raid-003', name: '精选召唤券', tier: 'A', reward: { itemType: 16, itemId: 510, quantity: 1 }, cost: 50, limitTotal: 10, source: 'screenshot' },
      { id: 'guild-raid-004', name: '专属武器碎片', tier: 'A', reward: { itemType: null, itemId: null, scoreKey: GUILD_RAID_UNIQUE_WEAPON_FRAGMENT_KEY, quantity: 10 }, cost: 185, limitTotal: null, source: 'screenshot' },
      { id: 'guild-raid-005', name: '魔女的心片(SR)', tier: 'A', reward: { itemType: 17, itemId: 28, quantity: 20 }, cost: 75, limitTotal: 15, source: 'screenshot' },
      { id: 'guild-raid-006', name: '魔女的心片(R)', tier: 'A', reward: { itemType: 17, itemId: 27, quantity: 60 }, cost: 40, limitTotal: 99, source: 'screenshot' },
      { id: 'guild-raid-007', name: '魔女的心片(R)', tier: 'B', reward: { itemType: 17, itemId: 27, quantity: 20 }, cost: 15, limitTotal: 199, source: 'screenshot' },
      { id: 'guild-raid-008', name: '生命树之露', tier: 'A', reward: { itemType: 24, itemId: 1, quantity: 5 }, cost: 300, limitTotal: 1, source: 'screenshot' },
      { id: 'guild-raid-009', name: '符石兑换券', tier: 'A', reward: { itemType: 13, itemId: 4, quantity: 60 }, cost: 150, limitTotal: 15, source: 'screenshot' },
      { id: 'guild-raid-010', name: '符石兑换券', tier: 'B', reward: { itemType: 13, itemId: 4, quantity: 5 }, cost: 15, limitTotal: 799, source: 'screenshot' },
      { id: 'guild-raid-011', name: '强化水', tier: 'A', reward: { itemType: 12, itemId: 1, quantity: 300 }, cost: 55, limitTotal: 15, source: 'screenshot' },
      { id: 'guild-raid-012', name: '强化水', tier: 'B', reward: { itemType: 12, itemId: 1, quantity: 20 }, cost: 4, limitTotal: 699, source: 'screenshot' },
      { id: 'guild-raid-013', name: '强化秘药', tier: 'A', reward: { itemType: 12, itemId: 2, quantity: 20 }, cost: 50, limitTotal: 15, source: 'screenshot' },
      { id: 'guild-raid-014', name: '强化秘药', tier: 'B', reward: { itemType: 12, itemId: 2, quantity: 2 }, cost: 6, limitTotal: 499, source: 'screenshot' },
      { id: 'guild-raid-015', name: '魔装高级香油', tier: 'A', reward: { itemType: 15, itemId: 2, quantity: 2 }, cost: 380, limitTotal: 5, source: 'screenshot' },
      { id: 'guild-raid-016', name: '魔装香油', tier: 'A', reward: { itemType: 15, itemId: 1, quantity: 3 }, cost: 200, limitTotal: 5, source: 'screenshot' },
      { id: 'guild-raid-017', name: '魔装香油', tier: 'B', reward: { itemType: 15, itemId: 1, quantity: 1 }, cost: 75, limitTotal: 59, source: 'screenshot' },
      { id: 'guild-raid-018', name: '精炼钢', tier: 'A', reward: { itemType: 13, itemId: 2, quantity: 15000 }, cost: 80, limitTotal: 5, source: 'screenshot' },
      { id: 'guild-raid-019', name: '精炼钢', tier: 'B', reward: { itemType: 13, itemId: 2, quantity: 10000 }, cost: 60, limitTotal: 35, source: 'screenshot' },
      { id: 'guild-raid-020', name: '圣装钢', tier: 'A', reward: { itemType: 13, itemId: 3, quantity: 1500 }, cost: 120, limitTotal: 5, source: 'screenshot' },
      { id: 'guild-raid-021', name: '圣装钢', tier: 'B', reward: { itemType: 13, itemId: 3, quantity: 1000 }, cost: 90, limitTotal: 35, source: 'screenshot' },
      { id: 'guild-raid-022', name: '未鉴定符石Lv6', tier: 'A', reward: { itemType: 17, itemId: 9, quantity: 1 }, cost: 16, limitTotal: 20, source: 'screenshot' },
      { id: 'guild-raid-023', name: '未鉴定符石Lv5', tier: 'A', reward: { itemType: 17, itemId: 8, quantity: 1 }, cost: 8, limitTotal: 20, source: 'screenshot' },
      { id: 'guild-raid-024', name: '未鉴定符石Lv4', tier: 'A', reward: { itemType: 17, itemId: 7, quantity: 1 }, cost: 4, limitTotal: 20, source: 'screenshot' },
      { id: 'guild-raid-025', name: '未鉴定符石Lv3', tier: 'A', reward: { itemType: 17, itemId: 6, quantity: 1 }, cost: 2, limitTotal: 20, source: 'screenshot' },
      { id: 'guild-raid-026', name: '未鉴定符石Lv2', tier: 'A', reward: { itemType: 17, itemId: 5, quantity: 1 }, cost: 1, limitTotal: 20, source: 'screenshot' },
      { id: 'guild-raid-027', name: '上级封印宝箱', tier: 'A', reward: { itemType: 17, itemId: 37, quantity: 1 }, cost: 60, limitTotal: 25, source: 'screenshot' },
      { id: 'guild-raid-028', name: '中级封印宝箱', tier: 'A', reward: { itemType: 17, itemId: 36, quantity: 1 }, cost: 30, limitTotal: 50, source: 'screenshot' },
      { id: 'guild-raid-029', name: '初级封印宝箱', tier: 'A', reward: { itemType: 17, itemId: 35, quantity: 1 }, cost: 15, limitTotal: 100, source: 'screenshot' },
      { id: 'guild-raid-030', name: '上级封印钥匙', tier: 'A', reward: { itemType: 18, itemId: 3, quantity: 1 }, cost: 4, limitTotal: null, source: 'screenshot' },
      { id: 'guild-raid-031', name: '中级封印钥匙', tier: 'A', reward: { itemType: 18, itemId: 2, quantity: 1 }, cost: 2, limitTotal: null, source: 'screenshot' },
      { id: 'guild-raid-032', name: '初级封印钥匙', tier: 'A', reward: { itemType: 18, itemId: 1, quantity: 1 }, cost: 1, limitTotal: null, source: 'screenshot' },
    ],
  },
  {
    shopKey: 'premium-shop',
    ...names('精品店', '精品店', 'Special', 'スペシャル', '특별'),
    shopName: '精品店',
    tradeShopTabId: 13,
    currency: { itemType: 1, itemId: 1, iconId: 1, ...names('免费钻石', '免費鑽石', 'Free Diamonds', '無償ダイヤ', '무료 다이아') },
    products: [
      {
        id: 'premium-shop-076',
        treasureChestId: 76,
        ...names('武具强化材料礼盒', '武具強化材料禮盒', 'Gear Upgrade Gift', '武具強化素材ギフト', '무구 강화 재료 기프트'),
        iconId: 92,
        reward: { itemType: 9, itemId: 76, quantity: 1 },
        contents: [
          { itemType: 12, itemId: 2, quantity: 200 },
          { itemType: 13, itemId: 4, quantity: 200 },
        ],
        cost: 9900,
        limitTotal: 1,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-080',
        treasureChestId: 80,
        ...names('圣装钢礼盒', '聖裝鋼禮盒', 'Holy Fragment Gift', '聖装鋼ギフト', '성장강 기프트'),
        iconId: 95,
        reward: { itemType: 9, itemId: 80, quantity: 1 },
        contents: [
          { itemType: 13, itemId: 3, quantity: 48000 },
          { itemType: 12, itemId: 2, quantity: 100 },
        ],
        cost: 9900,
        limitTotal: 1,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-081',
        treasureChestId: 81,
        ...names('精炼钢礼盒', '精煉鋼禮盒', 'Fragment Gift', '精錬鋼ギフト', '제련강 기프트'),
        iconId: 96,
        reward: { itemType: 9, itemId: 81, quantity: 1 },
        contents: [
          { itemType: 13, itemId: 2, quantity: 580000 },
          { itemType: 12, itemId: 2, quantity: 100 },
        ],
        cost: 9900,
        limitTotal: 1,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-082',
        treasureChestId: 82,
        ...names('金币礼盒', '金幣禮盒', 'Gold Gift', 'ゴールドギフト', '골드 기프트'),
        iconId: 101,
        reward: { itemType: 9, itemId: 82, quantity: 1 },
        contents: [
          { itemType: 10, itemId: 5, quantity: 3 },
          { itemType: 12, itemId: 1, quantity: 800 },
        ],
        cost: 1200,
        limitTotal: 3,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-083',
        treasureChestId: 83,
        ...names('封印宝箱礼盒', '封印寶箱禮盒', 'Sealed Chest Gift', '封印の宝箱ギフト', '봉인의 보물상자 기프트'),
        iconId: 102,
        reward: { itemType: 9, itemId: 83, quantity: 1 },
        contents: [
          { itemType: 17, itemId: 35, quantity: 5 },
          { itemType: 17, itemId: 36, quantity: 10 },
          { itemType: 17, itemId: 37, quantity: 20 },
          { itemType: 19, itemId: 1, quantity: 16 },
          { itemType: 10, itemId: 11, quantity: 1 },
        ],
        cost: 1560,
        limitTotal: 3,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-084',
        treasureChestId: 84,
        ...names('封印钥匙礼盒', '封印鑰匙禮盒', 'Sealed Key Gift', '封印の鍵ギフト', '봉인의 열쇠 기프트'),
        iconId: 103,
        reward: { itemType: 9, itemId: 84, quantity: 1 },
        contents: [
          { itemType: 18, itemId: 1, quantity: 10 },
          { itemType: 18, itemId: 2, quantity: 20 },
          { itemType: 18, itemId: 3, quantity: 50 },
          { itemType: 20, itemId: 1, quantity: 16 },
          { itemType: 10, itemId: 11, quantity: 1 },
        ],
        cost: 1560,
        limitTotal: 3,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-085',
        treasureChestId: 85,
        ...names('魔女的来信(R・忧蓝)礼袋', '魔女的來信(R．憂藍)禮袋', 'Witch’s Letter (R/Azure) Gift', '魔女の手紙（R・藍）ギフト', '마녀의 편지 (R・남청) 기프트'),
        iconId: 104,
        reward: { itemType: 9, itemId: 85, quantity: 1 },
        contents: [
          { itemType: 17, itemId: 17, quantity: 3 },
          { itemType: 19, itemId: 1, quantity: 4 },
          { itemType: 20, itemId: 1, quantity: 4 },
        ],
        cost: 660,
        limitTotal: 1,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-086',
        treasureChestId: 86,
        ...names('魔女的来信(R・业红)礼袋', '魔女的來信(R．業紅)禮袋', 'Witch’s Letter (R/Crimson) Gift', '魔女の手紙（R・紅）ギフト', '마녀의 편지 (R・홍염) 기프트'),
        iconId: 104,
        reward: { itemType: 9, itemId: 86, quantity: 1 },
        contents: [
          { itemType: 17, itemId: 18, quantity: 3 },
          { itemType: 19, itemId: 1, quantity: 4 },
          { itemType: 20, itemId: 1, quantity: 4 },
        ],
        cost: 660,
        limitTotal: 1,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-087',
        treasureChestId: 87,
        ...names('魔女的来信(R・苍翠)礼袋', '魔女的來信(R．蒼翠)禮袋', 'Witch’s Letter (R/Emerald) Gift', '魔女の手紙（R・翠）ギフト', '마녀의 편지 (R・비취) 기프트'),
        iconId: 104,
        reward: { itemType: 9, itemId: 87, quantity: 1 },
        contents: [
          { itemType: 17, itemId: 19, quantity: 3 },
          { itemType: 19, itemId: 1, quantity: 4 },
          { itemType: 20, itemId: 1, quantity: 4 },
        ],
        cost: 660,
        limitTotal: 1,
        source: 'screenshot',
      },
      {
        id: 'premium-shop-088',
        treasureChestId: 88,
        ...names('魔女的来信(R・流金)礼袋', '魔女的來信(R．流金)禮袋', 'Witch’s Letter (R/Amber) Gift', '魔女の手紙（R・黄）ギフト', '마녀의 편지 (R・황철) 기프트'),
        iconId: 104,
        reward: { itemType: 9, itemId: 88, quantity: 1 },
        contents: [
          { itemType: 17, itemId: 20, quantity: 3 },
          { itemType: 19, itemId: 1, quantity: 4 },
          { itemType: 20, itemId: 1, quantity: 4 },
        ],
        cost: 660,
        limitTotal: 1,
        source: 'screenshot',
      },
    ],
  },
]
