// Append one raid character using the repository's already generated official catalog texts.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { requireMasterDirectory } from './lib/masterDirectory.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const master = requireMasterDirectory(process.argv[2], 'node scripts/append_raid_character_catalog_texts.mjs <master-directory> <character-id>')
const id = Number(process.argv[3])
if (!Number.isInteger(id) || id < 1) throw new Error('A positive character id is required')
const load = name => JSON.parse(fs.readFileSync(path.join(master, name), 'utf8'))
const active = load('ActiveSkillMB.json')
const passive = load('PassiveSkillMB.json')
const character = load('CharacterMB.json').find(record => record.Id === id)
if (!character) throw new Error(`Missing CharacterMB ${id}`)

for (const locale of ['zh-CN', 'zh-TW', 'en', 'ja', 'ko']) {
  const index = JSON.parse(fs.readFileSync(path.join(root, 'public/data/character-catalog', locale, 'index.json'), 'utf8'))
  if (!index.characters.some(record => record.id === id)) throw new Error(`Missing ${locale} catalog index character ${id}`)
  const shard = Math.floor((id - 1) / index.shardSize)
  const catalog = JSON.parse(fs.readFileSync(path.join(root, 'public/data/character-catalog', locale, 'details', `${shard}.json`), 'utf8')).characters.find(record => record.id === id)
  if (!catalog) throw new Error(`Missing ${locale} catalog character ${id}`)
  const entries = []
  for (const [kind, ids, records, infosKey] of [
    ['ActiveSkillMB', character.ActiveSkillIds, active, 'ActiveSkillInfos'],
    ['PassiveSkillMB', character.PassiveSkillIds, passive, 'PassiveSkillInfos'],
  ]) for (const skillId of ids) {
    const raw = records.find(record => record.Id === skillId)
    if (raw.NameKey === '*') continue
    const skill = catalog.skills.find(record => record.id === skillId)
    if (!skill) throw new Error(`Missing ${locale} skill ${skillId}`)
    const levels = raw[infosKey].map(info => {
      const exclusive = ({ 128: 1, 256: 2, 512: 3 })[info.EquipmentRarityFlags]
      const text = exclusive ? catalog.exclusiveEffects.find(effect => effect.level === exclusive)?.text
        : skill.levels.find(level => level.level === info.OrderNumber)?.text
      if (!text) throw new Error(`Missing ${locale} skill ${skillId} level ${info.OrderNumber}`)
      return { type: exclusive ? 'exclusive' : 'level', level: exclusive ?? info.OrderNumber, unlockLevel: info.CharacterLevel, text }
    })
    entries.push({ slot: skill.slot, source: kind, id: skillId, name: skill.name, levels })
  }
  const file = path.join(root, 'src/constants/raid/characterMbTexts', `${locale}.js`)
  const { RAID_CHARACTER_MB_TEXTS } = await import(pathToFileURL(file).href)
  const texts = { ...RAID_CHARACTER_MB_TEXTS, [id]: entries }
  fs.writeFileSync(file, '// Generated by scripts/generate_raid_character_mb_texts.mjs (catalog append: scripts/append_raid_character_catalog_texts.mjs). Do not edit manually.\nexport const RAID_CHARACTER_MB_TEXTS = Object.freeze('+JSON.stringify(texts, null, 2)+')\n')
}
console.log(`Appended official catalog skill texts for raid character ${id} in five locales.`)
