import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { RAID_TABLE_ROSTER } from '../src/constants/raid/characters/index.js'

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const masterDir = path.join(projectRoot, 'data', 'Master')

function loadMaster(filename) {
  return JSON.parse(fs.readFileSync(path.join(masterDir, filename), 'utf8'))
}

const characters = new Map(loadMaster('CharacterMB.json').map(character => [character.Id, character]))
const activeSkills = new Map(loadMaster('ActiveSkillMB.json').map(skill => [skill.Id, skill]))
const passiveSkills = new Map(loadMaster('PassiveSkillMB.json').map(skill => [skill.Id, skill]))

const output = {}
for (const characterId of RAID_TABLE_ROSTER) {
  const character = characters.get(characterId)
  if (!character) throw new Error(`CharacterMB is missing raid character ${characterId}`)

  output[characterId] = [
    ...(character.ActiveSkillIds ?? []).map((skillId, index) => ({
      slot: `S${index + 1}`,
      source: 'ActiveSkillMB',
      id: skillId,
      memo: activeSkills.get(skillId)?.Memo,
    })),
    ...(character.PassiveSkillIds ?? []).map((skillId, index) => ({
      slot: `P${index + 1}`,
      source: 'PassiveSkillMB',
      id: skillId,
      memo: passiveSkills.get(skillId)?.Memo,
    })),
  ]

  const missing = output[characterId].filter(skill => typeof skill.memo !== 'string' || !skill.memo.trim())
  if (missing.length) throw new Error(`Missing MB Memo for character ${characterId}: ${missing.map(skill => skill.id).join(', ')}`)
}

const destination = path.join(projectRoot, 'src', 'constants', 'raid', 'characterMbTexts.js')
const banner = '// Generated by scripts/generate_raid_character_mb_texts.mjs. Do not edit manually.\n'
const source = `${banner}export const RAID_CHARACTER_MB_TEXTS = Object.freeze(${JSON.stringify(output, null, 2)})\n`
fs.writeFileSync(destination, source, 'utf8')
console.log(`Generated ${destination} for ${RAID_TABLE_ROSTER.length} raid characters.`)
