import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadRaidCharacterMbTexts } from '../src/constants/raid/characterMbTexts.js'
import { downloadMoonheartIcon } from './sync_assets.js'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const destDir = path.join(root, 'public/images/skills')
const base = 'https://list.moonheart.dev/p/public/mmtm/AddressableConvertAssets/Icon/Skill'
const characters = await loadRaidCharacterMbTexts('zh-CN')
const available = new Set()
let downloaded = 0
for (const id of new Set(Object.values(characters).flat().map(skill => skill.id))) {
  const result = await downloadMoonheartIcon(id, {
    destDir, url: `${base}/CSK_${String(id).padStart(9, '0')}.png`,
  })
  if (result.status === 'unavailable') {
    const message = `Moonheart skill icon ${id} is not available yet; it will be retried on the next run.`
    console.warn(message)
    if (process.env.GITHUB_ACTIONS === 'true') console.log(`::warning::${message}`)
  } else {
    available.add(id)
    if (result.status === 'downloaded') downloaded++
  }
}
const manifest = Object.fromEntries(Object.entries(characters).map(([id, skills]) => [id,
  Object.fromEntries(skills.map(skill => [skill.slot, available.has(skill.id) ? skill.id : null])),
]))
fs.writeFileSync(path.join(root, 'src/constants/raid/skillIcons.js'),
  '// Generated by scripts/sync_raid_skill_icons.mjs.\nexport const RAID_SKILL_ICONS = Object.freeze(' + JSON.stringify(manifest, null, 2) + ')\n')
console.log(`${available.size} skill icons available; ${downloaded} downloaded.`)
